### PR TITLE
Avoid lazy loading views issue

### PR DESCRIPTION
**Pull request by Ivanca**
Avoid lazy loading views issues found after installing on staging

### CODE REVIEW

**Comment by felipemontoya** [comment]
If this is all that is needed, I'm cool with that

**Review by felipemontoya — APPROVED** [review]

**Comment by felipemontoya** [comment]
We do need to bump the minor so I can install

**Comment by Ivanca** [comment]
@felipemontoya bumped

**Comment by felipemontoya** [comment]
@Ivanca thanks a bunch. I would have bumped the minor version for this, but what is done is done now

**Pull request merged**
